linuxmugello/blog/urls.py
from django.urls import path

from . import views
app_name = 'blog'
urlpatterns = [
    
    path('', views.index, name='index'),
   
    path('specifics/<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/', views.detail, name='detail'),
    
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    
    path('<int:question_id>/vote/', views.vote, name='vote'),
    
    path('menu/', views.menu, name='menu'),
    
    path('newss/', views.newss, name='newss'),
    
    path('news_one/', views.news_one, name='news_one'),
    
    path('slide/', views.slide, name='slide'),

]

linuxmugello/linuxmugello/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('blog/', include('blog.urls')),
    path('web/', include('web.urls')),
    path('admin/', admin.site.urls),
]

linuxmugello/web/urls.py
from django.urls import path

from . import views
app_name = 'web'
urlpatterns = [
    
    path('', views.index, name='index'),
   
    path('specifics/<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/', views.detail, name='detail'),
    
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    
    path('<int:question_id>/vote/', views.vote, name='vote'),
    
    path('menu/', views.menu, name='menu'),
    
    path('newss/', views.newss, name='newss'),
    
    path('news_one/', views.news_one, name='news_one'),
    
    path('slide/', views.slide, name='slide'),

]

linuxmugello/web/models.py
import datetime

from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

linuxmugello/blog/views.py
from  Connect import Connect
from .models import Choice, Question
from django.views import generic
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.shortcuts import render
import json
from django.http import JsonResponse
def results(request, question_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % question_id)

def vote(request, question_id):
    return HttpResponse("You're voting on question %s." % question_id)

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list, 'menu': Connect.menu(""), 'submenu': Connect.submnu(""), 'pagina':Connect.body("", "sanpiero"),'luogo':"sanpiero",'manifestazione':"news", 'news':Connect.news(""), 'urlx': " di Carlo Zanieri"}
    return render(request, 'blog/news.html', context)

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'blog/results.html'

def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request, 'blog/detail.html', {'question': question})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'blog/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('blog:results', args=(question.id,)))

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'blog/results.html', {'question': question})

def menu(request):
        menux=Connect.menu("")
        submenux=Connect.submnu("")
        context = {'menu': Connect.menu(""), 'submenu': Connect.submnu(""), 'mimetype':'application/json'}
        return render(request, 'blog/menu.html',context)
 
def newss(request):
                
        context = {'pagina':Connect.body("", "sanpiero"), 'manifestazione':"Blog", 'news':Connect.news(""), 'urlx':"html"}
        return render(request, 'blog/news.html',context)
  
def news_one(request):
        #titolo=request.POST['titolo']
        id=request.POST['id']
        context = {'pagina':Connect.body("", "sanpiero"), 'manifestazione':"news", 'news':Connect.news_one("",id)}
        return render(request, 'blog/news_one.html',context)
            
def slide(request):
        luogo="sanpiero"
        context = {'luogo' : luogo, 'slider':Connect.slider("", "index"),'menu': Connect.menu("")}
        return render(request, 'blog/nivo.html',context)      

linuxmugello/web/views.py
from  Connect import Connect
from .models import Choice, Question
from django.views import generic
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.shortcuts import render
import json
from django.http import JsonResponse
def results(request, question_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % question_id)

def vote(request, question_id):
    return HttpResponse("You're voting on question %s." % question_id)

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list, 'menu': Connect.menu(""), 'submenu': Connect.submnu(""), 'pagina':Connect.body("", "sanpiero"),'luogo':"sanpiero",'manifestazione':"news", 'news':Connect.news(""), 'urlx': " di Carlo Zanieri"}
    return render(request, 'web/master.html', context)

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'web/results.html'

def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request, 'web/detail.html', {'question': question})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'web/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('web:results', args=(question.id,)))

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'web/results.html', {'question': question})

def menu(request):
        menux=Connect.menu("")
        submenux=Connect.submnu("")
        context = {'menu': Connect.menu(""), 'submenu': Connect.submnu(""), 'mimetype':'application/json'}
        return render(request, 'web/menu.html',context)
 
def newss(request):
                
        context = {'pagina':Connect.body("", "sanpiero"), 'manifestazione':"web", 'news':Connect.news(""), 'urlx':"html"}
        return render(request, 'web/news.html',context)
  
def news_one(request):
        #titolo=request.POST['titolo']
        id=request.POST['id']
        context = {'pagina':Connect.body("", "sanpiero"), 'manifestazione':"news", 'news':Connect.news_one("",id)}
        return render(request, 'web/news_one.html',context)
            
def slide(request):
        luogo="sanpiero"
        context = {'luogo' : luogo, 'slider':Connect.slider("", "index"),'menu': Connect.menu("")}
        return render(request, 'web/nivo.html',context)      

linuxmugello/blog/templates/blog/index.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
<link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}">
<script type='text/javascript' src='https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js'></script>
<link rel="shortcut icon" href="{% static 'blog/favicon.ico' %}"/>
</head>
{% include "blog/menu.html" %}
<body>
    
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
    <li><a href="{% url 'detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No blog are available.</p>
{% endif %}
</body>
</html>

linuxmugello/blog/templates/blog/master.html
<!DOCTYPE html>
<html lang="en">
	{% load static %}
<head>
	<meta charset="utf-8"/>
	<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1"/>
	<link href="https://fonts.googleapis.com/css?family=Exo+2:300,400" rel="stylesheet"/>

	<title>Blog by Carlo Zanieri {{urlx}}</title>

		<meta name="author" content="Carlo Zanieri" />
		<link rel="shortcut icon" href="../favicon.ico"/>
		<link rel="stylesheet" type="text/css" href="{% static 'blog/static/menu_6/css/default.css'%}" />
		<link rel="stylesheet" type="text/css" href="{% static 'blog/static/menu_6/css/component.css'%}" />
		<script src="{% static 'blog/static/menu_6/js/modernizr.custom.js'%}"></script>
		<link href='http://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'/>
		<link rel="stylesheet" type="text/css" href="{% static 'blog/static/menu_6/css/default.css'%}" />
		<link rel="stylesheet" type="text/css" href="{% static 'blog/static/menu_6/css/component.css'%}" />
    <!-- css files -->
    <link rel="stylesheet" href="{% static 'blog/static/MENU/css/style.css'%}"/>
    <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"/>
    <!-- js files -->
    <style>
.content { margin:50px auto; max-width:728px; line-height:1.7}

    </style>
<style>

</style>
<script type='text/javascript' src='https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js'></script>

</head>
{% include "blog/menu.html" %}
<body>

		


				<div>


					<iframe  scrolling="no" width="100%" height="500 px" src="slide?luogo={{luogo}}" frameborder="0" style="padding-top:1%;"></iframe>

				</div>


<div   style="float:right; margin-left:1%; margin-right:1%;">
	
	<iframe  width="100%" height="500 px" src="newss" frameborder="0" style="padding-top:1%;"></iframe>
	 <iframe  width="100%" height="20%" src="{% static 'blog/static/riquadro.html'%}" frameborder="0" style="padding-top:2%;"></iframe>

<div class="video">
	<iframe width="20%" height="20%" src="https://www.youtube.com/embed/-lZO2ZzTWM4" frameborder="0"></iframe>
</div>



			</div>

					<p style="text-align: justify;  color:#7e342d; margin-right:15%;margin-left:15%;">

				  		<img  class="zoom" src= "{% static 'blog/static/img/'%}{{pagina.img}}" width="12%" height="12%" alt="" style="float: left; margin: 15px 15px 15px 15px;"/>{{pagina.testo}}

					  <img class="zoom" src="{% static 'blog/static/img/'%}{{pagina.img2}}" width="12%" height="12%" alt="" style="float: right; margin: 15px 15px 15px 15px;"/>{{pagina.testo2}}

					</p>




<footer>
	<h1 style="color:#000000; margin-left:30%; margin-right:25%; margin-top:10%; margin-bottom:5%;">Si ringraziano gli Sponsor</h1>
	<div class="flex" ><img  src="{% static 'blog/static/img/Sponsor SPS 2020.jpg'%}"/></div>
</footer>

</body>
</html>

linuxmugello/blog/templates/blog/menu.html
<!DOCTYPE html>
<html lang="en">
	{% load static %}
<head>
	<meta charset="utf-8">

	<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
	<link rel="shortcut icon" href="{% static 'blog/favicon.ico' %}">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Exo+2:300,400" >
	<script type='text/javascript' src='https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js'></script>
	<link rel="stylesheet" type="text/css" media="all" href="{% static 'blog/stellarnav/css/stellarnav.css' %}">

  <style>
.content { margin:5px auto; max-width:728px; line-height:1.7}

    </style>
<style>
/* styles for this sample only */
*{ margin: 0; padding: 0; }
body { height: 3200px; font-size: 16px; font-family: 'Exo 2', sans-serif; background: #efefef; color: #555; }
.header { text-align: center; }
.header a { padding: 30px 0 0; display: block; font-size: 48px; text-decoration: none; color: #555; }
.header p { margin: 10px 0 40px 0; font-size: 18px; }
.container { max-width: 1200px; margin: 0 auto; }
@media only screen and (max-width : 1000px) {
	.stellarnav > ul > li > a { padding: 20px 23px; }
}
/* styles for this sample only */
</style>
</head>


<body>

<img src="{% static 'blog/static/img/logo.jpg' %}" width="7%" height="3.5%" style="float: left;"/><p style=" display: inline; vertical-align: baseline; color:#7e342d; font-weight: bold; font-size: 96px; align: center; margin-left:25%"> Pro Loco <h1   style=" vertical-align: text-baseline; display: inline; color:#7e342d; font-size: 48px; text-align: center;" >S.Piero a Sieve</h1><img src="{% static 'blog/static/img/logo.jpg' %}" width="7%" height="3.5%" style="float: right;"/> </p>

	<div class="stellarnav">
		<ul>
			{% for menus in menu %}
			<li>

                				<a href="{{menus.link}}" class="gn-icon gn-icon-help">{{menus.titolo}}</a>

								<ul class="dl-submenu">
									{% for submenus in submenu %}
									<li >
											{% if menus.codice == submenus.radice %}
											<a href={{submenus.link}} ><span></span> {{submenus.titolo}}</a>
											{% endif %}
									</li>
									{% endfor %}
								</ul>
							</li>
			{% endfor%}

		</ul>
	</div>

	<script type="text/javascript" src="{% static 'blog/stellarnav/js/stellarnav.min.js' %}"></script>
	<script type="text/javascript">
		jQuery(document).ready(function($) {
			jQuery('.stellarnav').stellarNav({
				theme: 'dark',
				breakpoint: 960,
				position: 'right',
				phoneBtn: '18009997788',
				locationBtn: 'https://www.google.com/maps'
			});
		});
	</script>

</body>

</html>

linuxmugello/blog/templates/blog/news.html
<!DOCTYPE html>
<html lang="en">
  {% load static %}
<head>
  <meta charset="utf-8"/>
  <meta http-equiv="Content-Type" content="text/html"/>
  <title>Blog by Carlo Zanieri</title>
  <meta name="author" content="JCarlo Zanieri"/>
  <link rel="shortcut icon" href="http://static.tmimgcdn.com/img/favicon.ico"/>
  <link rel="icon" href="http://static.tmimgcdn.com/img/favicon.ico"/>
  <link rel="stylesheet" type="text/css" href="{% static 'blog/static/menu_6/css/default.css'%}" />
  <link rel="stylesheet" type="text/css" media="all" href="{% static 'blog/static/news/css/styles.css'%}"/>
  <script type="text/javascript" src="{% static 'blog/static/news/js/jquery-1.11.0.min.js'%}"></script>
  <script type="text/javascript" src="{% static 'blog/static/news/js/responsiveCarousel.min.js'%}"></script>
</head>

<body>
  <div id="w">
    <h1>BLOG {{urlx}}</h1>

    <nav class="slidernav">
      <div id="navbtns" class="clearfix">
        <a href="#" class="previous">prev</a>
        <a href="#" class="next">next</a>
      </div>
    </nav>

    <div class="crsl-items" data-navigation="navbtns">
      <div class="crsl-wrap">
       {% for newss in news %}
        <div class="crsl-item">
          <div class="thumbnail">
            <img  src= "{% static 'blog/static/news/img/'%}{{newss.img}}" alt="{{newss.img}}"></img>
            <span class="postdate">{{newss.date}}</span>
          </div>

          <h3><a href="#">{{newss.title}}</a></h3>

          <p>{{newss.html}}</p>
          <form action="news_one/ " method="post">
            {% csrf_token %}
            <input type="hidden" name="id" id="{{ newss.id }}" value="{{newss.id }}">
            <input type="submit" value="Leggi tutto">
          </form>
           <!-- <form action="/blog/news_one?id={{newss.id}}" method="post" accept-charset="utf-8" enctype="multipart/form-data" target="_parent">
            <input id="titolo" name="titolo" type="hidden" value="{{newss.title}}" />
            <input id="id" name="id" type="hidden" value="{{newss.id}}" />
            <input type="submit" value="readmore" />
          </form> 
         <p class="readmore"><a href="blog/news_one?request=request&amp;id={{newss.id}}"  target="_parent">Read More</a></p> -->
        </div>
      {% endfor %}

      </div><!-- @end .crsl-wrap -->
    </div><!-- @end .crsl-items -->

  </div><!-- @end #w -->
<script type="text/javascript">
$(function(){
  $('.crsl-items').carousel({
    visible: 6,
    itemMinWidth: 90,
    itemEqualHeight: 185,
    itemMargin: 9,
  });

  $("a[href=#]").on('click', function(e) {
    e.preventDefault();
  });
});
</script>
</body>
</html>

linuxmugello/blog/templates/blog/news_one.html
<!DOCTYPE html>
<html lang="en">
  {% load static %}
<head>
  <meta charset="utf-8"/>
  <meta http-equiv="Content-Type" content="text/html"/>
  <title></title>

  <link rel="shortcut icon" href="http://static.tmimgcdn.com/img/favicon.ico"/>
  <link rel="icon" href="http://static.tmimgcdn.com/img/favicon.ico"/>
  <link rel="stylesheet" type="text/css" href="{% static 'blog/static/menu_6/css/default.css'%}" />
  <link rel="stylesheet" type="text/css" media="all" href="{% static 'blog/static/news/css/styles.css'%}"/>
  <script type="text/javascript" src="{% static 'blog/static/news/js/jquery-1.11.0.min.js'%}"></script>
  <script type="text/javascript" src="{% static 'blog/static/news/js/responsiveCarousel.min.js'%}"></script>
</head>

<body>
<h1>{{titolo}}</h1>
  <div id="w" style="margin-left:30%;">



    <div class="crsl-items" data-navigation="navbtns">
      <div class="crsl-wrap">
        {% for newss in news %}
        <div class="crsl-item">
          <div class="thumbnail">
            <img  src= "{% static 'blog/static/news/img/'%}{{newss.img}}" alt="{{newss.img}}"/>
            <span class="postdate">{{newss.date}}</span>
          </div>

          <h3><a href="#">{{newss.title}}</a></h3>

          <p>{{newss.html}}</p>

          <p class="readmore"><a href="/blog">Go Back &raquo;</a></p>
        </div><!-- post #1 -->
        {%endfor%}

      </div><!-- @end .crsl-wrap -->
    </div><!-- @end .crsl-items -->

  </div><!-- @end #w -->
<script type="text/javascript">
$(function(){
  $('.crsl-items').carousel({
    visible: 3,
    itemMinWidth: 90,
    itemEqualHeight: 185,
    itemMargin: 9,
  });

  $("a[href=#]").on('click', function(e) {
    e.preventDefault();
  });
});
</script>
</body>
</html>

linuxmugello/blog/templates/blog/nivo.html
<!DOCTYPE html>
{% load static %}
<html lang="en" class="no-js">
<head>


    <title></title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0;"/>
	<script type='text/javascript' src='https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js'></script>
	<link rel="shortcut icon" href="{% static 'blog/favicon.ico' %}"/>
    <link rel="stylesheet" href="{% static 'blog/static/nivo-slider/css/nivo-slider.css'%}" type="text/css" media="screen" />
    <link href='http://fonts.googleapis.com/css?family=Dosis:400,600,300' rel='stylesheet' type='text/css'/>

    <script type="text/javascript" src="{% static 'blog/static/nivo-slider/js/jquery-1.7.1.min.js'%}"></script>
    <script type="text/javascript" src="{% static 'blog/static/nivo-slider/js/jquery.nivo.slider.js'%}"></script>
    <script type="text/javascript">

	function captionMoveIn() {
		$('.nivo-caption')
		.fadeIn("fast")
		.animate({left: "0px"},1400)
	;};


	function captionMoveOut() {
		$('.nivo-caption')
		.animate({left: "-400px"},1400)
		.fadeOut("fast")
	;};

	</script>
    <script type="text/javascript">
	$(window).load(function() {
		$('#slider').nivoSlider({
	        effect:"sliceUpDownLeft",
	        pauseTime:6000,
			animSpeed:850,
			afterLoad: function (){captionMoveIn();},
	        beforeChange: function (){captionMoveOut();captionMoveIn();}

	    });
	});
	</script>

</head>

<body >
	
    <div   id="wrapper">


	<div class="slider-wrapper">
	    <div   id="slider" class="nivoSlider">
			{% for sliders in slider %}

			<span>
			<img class="zoom" src= "{% static 'blog/static/img/'%}{{sliders.codice}}/{{sliders.img}}" alt="" title="#htmlcaption{{sliders.id}}" />
			</span>
			{% endfor %}
	    </div>

	</div>
	
{% for sliders in slider %}
    <div id="htmlcaption{{sliders.id}}" class="nivo-html-caption">

		<h1><a style="color:#000000;" href="{{sliders.link}}">{{sliders.titolo}}</a></h1>
	    <p> {{sliders.caption}} <a href="">Continua...</a>{{sliders.img}}</p>

	</div>
{% endfor %}
	</div>


</body>
</html>

linuxmugello/blog/templates/blog/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'blog:detail' question.id %}">Vote again?</a>

linuxmugello/web/templates/web/detail.html
<form action="{% url 'vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
    </form>

linuxmugello/web/templates/web/index.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
<link rel="stylesheet" type="text/css" href="{% static 'web/style.css' %}">
<script type='text/javascript' src='https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js'></script>
<link rel="shortcut icon" href="{% static 'web/favicon.ico' %}"/>
</head>
{% include "web/menu.html" %}
<body>
    
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
    <li><a href="{% url 'detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No web are available.</p>
{% endif %}
</body>
</html>

linuxmugello/web/templates/web/index_new.html
<meta http-equiv="refresh" content="0; URL=http://linuxmugello.net:8888">

linuxmugello/web/templates/web/master.html
<!DOCTYPE html>
<html lang="en">
	{% load static %}
<head>
	<meta charset="utf-8"/>
	<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1"/>
	<link href="https://fonts.googleapis.com/css?family=Exo+2:300,400" rel="stylesheet"/>

	<title>web by Carlo Zanieri {{urlx}}</title>

		<meta name="author" content="Carlo Zanieri" />
		<link rel="shortcut icon" href="../favicon.ico"/>
		<link rel="stylesheet" type="text/css" href="{% static 'web/static/menu_6/css/default.css'%}" />
		<link rel="stylesheet" type="text/css" href="{% static 'web/static/menu_6/css/component.css'%}" />
		<script src="{% static 'web/static/menu_6/js/modernizr.custom.js'%}"></script>
		<link href='http://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'/>
		<link rel="stylesheet" type="text/css" href="{% static 'web/static/menu_6/css/default.css'%}" />
		<link rel="stylesheet" type="text/css" href="{% static 'web/static/menu_6/css/component.css'%}" />
    <!-- css files -->
    <link rel="stylesheet" href="{% static 'web/static/MENU/css/style.css'%}"/>
    <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"/>
    <!-- js files -->
    <style>
.content { margin:50px auto; max-width:728px; line-height:1.7}

    </style>
<style>

</style>
<script type='text/javascript' src='https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js'></script>

</head>
{% include "web/menu.html" %}
<body>

		


				<div>


					<iframe  scrolling="no" width="100%" height="500 px" src="slide?luogo={{luogo}}" frameborder="0" style="padding-top:1%;"></iframe>

				</div>


<div   style="float:right; margin-left:1%; margin-right:1%;">
	
	<iframe  width="100%" height="500 px" src="newss" frameborder="0" style="padding-top:1%;"></iframe>
	 <iframe  width="100%" height="20%" src="{% static 'web/static/riquadro.html'%}" frameborder="0" style="padding-top:2%;"></iframe>

<div class="video">
	<iframe width="20%" height="20%" src="https://www.youtube.com/embed/-lZO2ZzTWM4" frameborder="0"></iframe>
</div>



			</div>

					<p style="text-align: justify;  color:#7e342d; margin-right:15%;margin-left:15%;">

				  		<img  class="zoom" src= "{% static 'web/static/img/'%}{{pagina.img}}" width="12%" height="12%" alt="" style="float: left; margin: 15px 15px 15px 15px;"/>{{pagina.testo}}

					  <img class="zoom" src="{% static 'web/static/img/'%}{{pagina.img2}}" width="12%" height="12%" alt="" style="float: right; margin: 15px 15px 15px 15px;"/>{{pagina.testo2}}

					</p>




<footer>
	<h1 style="color:#000000; margin-left:30%; margin-right:25%; margin-top:10%; margin-bottom:5%;">Si ringraziano gli Sponsor</h1>
	<div class="flex" ><img  src="{% static 'web/static/img/Sponsor SPS 2020.jpg'%}"/></div>
</footer>

</body>
</html>

linuxmugello/web/templates/web/mytemplate.html
{% extends "master.html" %}

{% block content %}

<div class="content">

</div>
{% endblock content %}

linuxmugello/web/templates/web/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'web:detail' question.id %}">Vote again?</a>